version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: todoapi_database
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  api:
    container_name: todoapi
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_URLS: ${ASPNETCORE_URLS}
      ConnectionStrings__DbConnectionString: ${DB_CONNECTION_STRING}      
    ports:
      - 5040:80
    restart: always
